push (42)
push int32(45.2)
push string("aasdfouh")
push double(1)
push double("")
push double("uiygfewviu.ouhwerfouh")
push double(oiuhgerfoihev)
push double(oiuhge.rfoihev)
push int(oiuhgerfoihev)
exit
